---
 - hosts: Master
   become: true

   tasks:
    - name: Clone Application Repo
      shell: git clone https://github.com/microservices-demo/microservices-demo.git

    - name: Deploying Socks-Shop to master
      become_user: ubuntu
      shell: kubectl create -f microservices-demo/deploy/kubernetes/complete-demo.yaml
